# Los archivos docker-compose.yml son versionados, lo que significa que es muy importante indicar la versión de las instrucciones que queremos darle.
version: "3.3"

# Servidor nginx
services:
  nginx:
    # versión
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    # Puerto 80
    ports:
      - "80:80"
    volumes:
      - ./laravel-project:/var/www/html
    networks:
      - webserver

  # Configuración de php
  php-fpm:
    build: 
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./laravel-project:/var/www/html
    networks:
      - webserver

networks:
  webserver:
    driver: bridge
